/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_socket_jni_testdemo */

#ifndef _Included_com_socket_jni_testdemo
#define _Included_com_socket_jni_testdemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_socket_jni_testdemo
 * Method:    sayYes
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_socket_jni_testdemo_sayYes
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
